#!/bin/bash

DIR="$( cd "$( dirname "$0" )" && pwd )"

case "$1" in
    init)
        vagrant up
        vagrant ssh -c "sudo /vagrant/script/env.sh update"
        vagrant ssh -c "sudo /vagrant/script/env.sh restart"
        gradle flywayMigrate war cargoDeployRemote
    ;;
    deploy)
	vagrant up
        gradle flywayMigrate war cargoRedeployRemote
    ;;
    ssh)
	vagrant up
        vagrant ssh
    ;;
    *)
	vagrant up
        vagrant ssh -c "sudo /vagrant/script/env.sh $1"
    ;;
esac

