apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
    app: sr
    role: app
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    name: api
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: api-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: api
        app: sr
        role: app
    spec:
      containers:
      - name: api
        image: gcr.io/subrosagames.com/subrosagames/api:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
