apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    name: config
    app: sr
    role: config
spec:
  type: NodePort
  ports:
  - port: 8888
    protocol: TCP
    name: http
  selector:
    name: config
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: config-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: config
        app: sr
        role: config
    spec:
      containers:
      - name: config
        image: gcr.io/subrosagames.com/subrosagames/config
        ports:
        - containerPort: 8888
        env:
          - name: SEC_CONFIG_REPO_USER
            value: josiahgore@gmail.com
          - name: SEC_CONFIG_REPO_PASS
            value: 3848f6c1fa30b0bc2558238e672b4325ca1aebeb
        imagePullPolicy: Always
