apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    name: gateway
    app: sr
    role: app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    name: gateway
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gateway-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gateway
        app: sr
        role: app
    spec:
      containers:
      - name: gateway
        image: gcr.io/subrosagames.com/subrosagames/gateway
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
