apiVersion: v1
kind: Service
metadata:
  name: image
  labels:
    name: image
    app: sr
    role: app
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    name: image
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: image-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: image
        app: sr
        role: app
    spec:
      containers:
      - name: image
        image: gcr.io/subrosagames.com/subrosagames/image
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
