apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
    app: sr
spec:
  ports:
  - port: 8080
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    name: api
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: api-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: api
        app: sr
    spec:
      containers:
      - name: api
        image: java:8
        command: ['java', '-jar', '/var/code/apps/api/build/libs/subrosa-api-1.0.0-SNAPSHOT.jar']
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: root
          mountPath: /var/code
      volumes:
      - name: root
        hostPath:
          path: /vagrant
