apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    name: gateway
    app: sr
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30000
    protocol: TCP
    name: http
  selector:
    name: gateway
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gateway-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gateway
        app: sr
    spec:
      containers:
      - name: gateway
        image: java:8
        command: ['java', '-jar', '/var/code/apps/gateway/build/libs/subrosa-gateway-1.0.0-SNAPSHOT.jar']
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: root
          mountPath: /var/code
      volumes:
      - name: root
        hostPath:
          path: /vagrant
