apiVersion: v1
kind: Service
metadata:
  name: image
  labels:
    name: image
    app: sr
spec:
  ports:
  - port: 8080
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    name: image
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: image-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: image
        app: sr
    spec:
      containers:
      - name: image
        image: java:8
        command: ['java', '-jar', '/var/code/apps/image/build/libs/subrosa-image-1.0.0-SNAPSHOT.jar']
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: root
          mountPath: /var/code
      volumes:
      - name: root
        hostPath:
          path: /vagrant
