logging:
  level:
    org.springframework: INFO
    com.subrosagames: DEBUG

spring:
  datasource:
    url: jdbc:hsqldb:mem:testdb
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbcDriver

  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format-sql: true
      use-sql-comments: true

