security:
  sessions: ALWAYS

spring:
  redis:
    host: redis

zuul:
  routes:
    api:
      path: /subrosa/v1/**
      url: http://api:8080
      stripPrefix: false
    image:
      path: /image/**
      url: http://image:8080
      stripPrefix: false

