zuul:
  stripPrefix: false
  routes:
    api:
      path: /subrosa/v1/**
      url: http://${API_PORT_8080_TCP_ADDR:localhost}:${API_PORT_8080_TCP_PORT:8080}
      stripPrefix: false
    image:
      path: /image/**
      url: http://${IMAGE_PORT_8080_TCP_ADDR:localhost}:${IMAGE_PORT_8080_TCP_PORT:8080}
      stripPrefix: false
