security:
  sessions: ALWAYS

spring:
  redis:
    host: ${REDIS_PORT_6379_TCP_ADDR}
  oauth2:
    client:
      client-id: subrosa
      client-secret: subrosa

zuul:
  routes:
    api:
      path: /subrosa/v1/**
      url: http://${API_PORT_8080_TCP_ADDR:api}:${API_PORT_8080_TCP_PORT:8080}
      stripPrefix: false
    image:
      path: /image/**
      url: http://${IMAGE_PORT_8080_TCP_ADDR:image}:${IMAGE_PORT_8080_TCP_PORT:8080}
      stripPrefix: false

